name: Sync to Azure

on:
  push:
    branches:
      - main   # change if needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push to Azure DevOps
        run: |
          git config --global user.email "Dinesh.Patil@gyrus.com"
          git config --global user.name "dinesh-gyrus"
          git remote add azure https://$(AZURE_PAT)@dev.azure.com/GyrusSystems/Gyrus%20Aim%20QA%20Automation%20V17/_git/Gyrus%20Aim%20QA%20Automation%20V17          
          git push azure HEAD:main --force
